version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
